name: first

on: push

jobs:
  job1:
    name: First Job Ubuntu
    runs-on: ubuntu-latest
    steps:
        - name: Step One Uses
          uses: actions/checkout@v2
        - name: Step Two
          run: env | sort

  job2:
      name: Second Job Windows
      runs-on: windows-latest
      steps:
          - name: Step One uses 
            uses: actions/checkout@v2
          - name: Step Two Run
            run: Get-ChildItem Env: | Sort-Object Name
